# Generated by Django 6.0.4 on 2026-05-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=100)),
                ('sal', models.FloatField()),
            ],
        ),
    ]
